spring:
  application:
    name: config-server
  server:
    port:8888
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ErikMarquesSilva/config-repo.git
          basedir: /Users/erik-marques/config-repo
          cloneOnStart: true